<?php
/**
 * Configuration file generated by FrilleZFTool
 *
 * The previous configuration file is stored in
 * ./module/Order/config/module.config.old
 *
 * @see https://github.com/RalfEggert/FrilleZFTool
 */


return array(
    'controllers'     => array(
        'factories' => array(
            'Order\Controller\Index' => 'Order\Controller\IndexControllerFactory'
        )
    ),
    'router'          => array(
        'routes' => array(
            'order' => array(
                'type'          => 'Literal',
                'options'       => array(
                    'route'    => '/order',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Order\Controller',
                        'controller'    => 'Index',
                        'action'        => 'index'
                    )
                ),
                'may_terminate' => true,
                'child_routes'  => array(
                    'index' => array(
                        'type'    => 'segment',
                        'options' => array(
                            'route'       => '/index[/:action[/:id]]',
                            'defaults'    => array('controller' => 'Index'),
                            'constraints' => array(
                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'id'     => '[0-9_-]*'
                            )
                        )
                    )
                )
            )
        )
    ),
    'view_manager'    => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
    'service_manager' => array(
        'factories' => array(
            'Order\Service'  => 'Order\Service\OrderServiceFactory',
            'Order\Listener' => 'Order\Listener\OrderListenerFactory',
        ),
    ),
    'log'             => array(
        'Order\Log' => array(
            'writers' => array(
                array(
                    'name'     => 'stream',
                    'priority' => 1000,
                    'options'  => array(
                        'stream' => APPLICATION_ROOT . '/data/log/order.log',
                    ),
                ),
            ),
        ),
    ),
);
