<?php
/**
 * This file was generated by FrilleZFTool.
 *
 * @package Order
 * @see https://github.com/RalfEggert/FrilleZFTool
 */


namespace Order\Controller;

use Order\Service\OrderService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

/**
 * Class IndexController
 *
 * Please add a proper description for the IndexController
 *
 * @package Order
 */
class IndexController extends AbstractActionController
{
    /**
     * @var OrderService
     */
    protected $orderService;

    /**
     * @param OrderService $orderService
     */
    public function setOrderService($orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * @return OrderService
     */
    public function getOrderService()
    {
        return $this->orderService;
    }

    /**
     * Method indexAction
     *
     * Please add a proper description for this action
     *
     * @return ViewModel
     */
    public function indexAction()
    {
        $newOrder = $this->getOrderService()->saveOrder();

        return new ViewModel(
            array(
                'newOrder' => $newOrder,
            )
        );
    }
}

