<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Listener\I18nListener'      => __DIR__ . '/src/Application/Listener/I18nListener.php',
  'Application\Listener\ViewListener'      => __DIR__ . '/src/Application/Listener/ViewListener.php',
  'Application\Mail\Transport\FileFactory' => __DIR__ . '/src/Application/Mail/Transport/FileFactory.php',
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Controller\I18nController'  => __DIR__ . '/src/Application/Controller/I18nController.php',
  'Application\Module'                     => __DIR__ . '/Module.php',
);
