<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'template_map'            => __DIR__ . '/view/template_map.php',
    'application/i18n/index'  => __DIR__ . '/view/application/i18n/index.phtml',
    'application/index/index' => __DIR__ . '/view/application/index/index.phtml',
    'error/index'             => __DIR__ . '/view/error/index.phtml',
    'error/404'               => __DIR__ . '/view/error/404.phtml',
    'layout/layout'           => __DIR__ . '/view/layout/layout.phtml',
);
