<?php
/**
 * Zend Framework 2 - MySkeletonApplication
 *
 * Gepimpte SkeletonApplication für das Zend Framework 2,
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Footer view script
 *
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>ZF2 - MySkeletonApplication</h4>
                <p>
                    Diese gepimpte SkeletonApplication kann als Basis für eigene Zend Framework 2 Applikationen verwendet werden. Sie
                    enthält ein <code style="font-size: 120%;">Application</code> Modul mit einigen grundlegenden Funktionalitäten, wie
                    mehrstufiges Layout, usw.
                </p>
                <p>
                    <a href="https://plus.google.com/105130475645941839411" target="_blank" class="btn btn-default">Feedback erwünscht!</a>
                </p>
            </div>
            <div class="col-md-4">
                <h4>Zend Framework Links</h4>
                <ul class="list-unstyled">
                    <li><a href="http://framework.zend.com/" target="_blank">Zend Framework Website</a></li>
                    <li><a href="http://zf2.readthedocs.org/" target="_blank">Zend Framework 2 Manual</a></li>
                    <li><a href="http://modules.zendframework.com/" target="_blank">Zend Framework 2 Module</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Weitere Links</h4>
                <ul class="list-unstyled">
                    <li><a href="https://github.com/RalfEggert/MySkeletonApplication" target="_blank">GitHub Repository für
                            MySkeletonApplication</a></li>
                    <li><a href="https://plus.google.com/105130475645941839411" target="_blank">Google+ Seite Ralf Eggert</a></li>
                    <li><a href="http://www.zendframeworkbuch.de/" target="_blank">Zend Framework Buch</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
