<?php
/**
 * Zend Framework 2 - MySkeletonApplication
 *
 * Gepimpte SkeletonApplication für das Zend Framework 2,
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Header view script
 *
 * @package    Application
 */

?>
<div class="top_line"></div>
<header>
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="logo col-xs-2">
                    <a href="/"><img alt="Zend Framework 2" title="Zend Framework 2" src="/img/zf2-logo.png" class="img-responsive"></a>
                </div>
                <div class="logo-text">
                    <h2><a href="/">MySkeletonApplication</a></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url('home'); ?>">Startseite</a></li>
                </ul>
            </div>
        </nav>
    </div>
</header>

