<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Order\Listener\OrderListener'            => __DIR__ . '/src/Order/Listener/OrderListener.php',
  'Order\Listener\OrderListenerFactory'     => __DIR__ . '/src/Order/Listener/OrderListenerFactory.php',
  'Order\Service\OrderService'              => __DIR__ . '/src/Order/Service/OrderService.php',
  'Order\Service\OrderServiceFactory'       => __DIR__ . '/src/Order/Service/OrderServiceFactory.php',
  'Order\Controller\IndexController'        => __DIR__ . '/src/Order/Controller/IndexController.php',
  'Order\Controller\IndexControllerFactory' => __DIR__ . '/src/Order/Controller/IndexControllerFactory.php',
  'Order\Module'                            => __DIR__ . '/Module.php',
);
