<?php
/**
 * This file was generated by FrilleZFTool.
 *
 * @package Order
 * @see     https://github.com/RalfEggert/FrilleZFTool
 */


namespace Order;

/**
 * Module
 *
 * Please add a proper description for the Order module
 *
 * @package Order
 */
class Module
{

    /**
     * Get module configuration
     *
     * @return array
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Get autoloader configuration
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\ClassMapAutoloader' => array(
                'Order' => __DIR__ . '/autoload_classmap.php',
            ),
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__
                )
            )
        );
    }


}

