<?php
/**
 * Zend Framework 2 - PHP-Magazin Event-Manager
 *
 * Beispiele für ZF2 Event-Manager
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Herzlich Willkommen!');

?>
<div class="jumbotron">
    <h1>Zend Framework 2 - PHP-Magazin Event-Manager</h1>
    <p>
        In diesem Projekt finden Sie die lauffähigen Beispiele für den Artikel
        zum Zend Framework 2 Event-Manager aus dem PHP Magazin.
    </p>
    <p>
        <a href="<?php echo $this->url('order') ?>" class="btn btn-primary">
            Neue Bestellung ausführen
        </a>
    </p>
</div>

