<?php
/**
 * Zend Framework 2 - MySkeletonApplication
 *
 * Gepimpte SkeletonApplication für das Zend Framework 2,
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Herzlich Willkommen!');

?>
<div class="jumbotron">
    <h1>Zend Framework 2 - MySkeletonApplication</h1>

    <p>Diese gepimpte SkeletonApplication kann als Basis für eigene Zend Framework 2 Applikationen verwendet werden. Sie enthält ein
        <code style="font-size: 120%;">Application</code> Modul mit einigen grundlegenden Funktionalitäten, wie mehrstufiges Layout,
        Application Management mit Stufen "development" und "production", usw.
    </p>
</div>

